//Disable some of the JSLint warnings
/*global window,console,Ext*/
(function(){
    //Make sure strict mode is on
    'use strict';
    
    /**
     * An example of the event data sent using the postMessage msg bus; This class is never instantiaded, its main purpose is documentation
     */
    Ext.define('mh.communication.PostMessageEvtData', {

        evenName: 'evt::name',

        /**
         * unique identifier of a sender. 
         * @property {string}
         */
        sender: 'unique identifier of a sender',

        /**
         * unique identifier of a recipient. allows specifing the id of a recipient (that should have been generated by him), so msg can be recognised by a desired target
         * this is important, when there are many frames loaded from the same origin
         * @property {string}
         */
        recipient: 'unique identifier of a recipient',

        /**
         * @property {Object} the actual event DTO
         */
        data: {}

        //check the event type. basically it should have the following properties:
        // {
        //     name: '', //broadcasted evt name
        //     data: {}, //whatever the data that needs to be passed
        //     target: '', 'parent', 'crossframe', 'children'
        //     drilldown: true / false //whether or not the events should be passed deeper in the stack by the children, that may contain some other frames
        //     bubble: true  /false //whether or not the events should be bubbled by the parents
        // }
    });

}());