//Disable some of the JSLint warnings
/*global window,console,Ext*/
(function(){
    //Make sure strict mode is on
    'use strict';
    
    /**
     * An example of the event data sent using the postMessage msg bus; This class is never instantiaded, its main purpose is documentation
     */
    Ext.define('mh.communication.PostMessageEvtData', {

        /**
         * @property {string} eventName
         */

        /**
         * @property {string} initiator
         * unique identifier of the event initiator. can be used to decide whether pass event back
         */

        /**
         * @property {string} sender
         * unique identifier of a sender.
         */

        /**
         * @property {string} recipient
         * unique identifier of a recipient. allows specifing the id of a recipient (that should have been generated by him), so msg can be recognised by a desired target
         * this is important, when there are many frames loaded from the same origin
         */

        /**
         * @property {Object} data
         * the actual event DTO
         */

        /**
         * @property {Object} eOpts
         * event brodcasting options
         * @property {Boolean} eOpts.host
         * if being hosted, will post msg to host
         * @property {Boolean} eOpts.hosted
         * if hosting, will post msg to hosted
         * @property {Boolean|Number} eOpts.bubble
         * just bubble the evt up the host stack; if number is provided it specifies the number of levels to bubble up the stack and then stop
         * @property {Boolean|Number} eOpts.drilldown
         * just bubble the evt down the hosted stack; if number is provided it specifies the number of levels to drill down the stack and then stop
         * @property {Number} currentLvl
         * the level below or above the event initiator
         */
    });

}());